// Content script for LinkedIn connection modal
// Adds button to auto-fill connection note with personalized template

const PASTE_BTN_CLASS = "papooga-paste-note-btn";

function generateConnectionNote(data: {
  name: string;
  title: string;
  company_name: string;
  company_linkedin_url: string;
}): string {
  // Extract first name
  const firstName = data.name.split(" ")[0];

  // Template with Lorem Ipsum placeholder
  // In the future, this will be generated by an LLM
  return `Hi ${firstName}, I noticed you're ${data.title} at ${data.company_name}. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Would love to connect and learn more about your work.`;
}

function extractCurrentProfileData(): {
  name: string;
  title: string;
  company_name: string;
  company_linkedin_url: string;
} | null {
  try {
    // Try to get data from the current page
    const nameElement =
      document.querySelector('[data-anonymize="person-name"]') ||
      document.querySelector(".artdeco-entity-lockup__title") ||
      document.querySelector(".pv-top-card--list li:first-child") ||
      document.querySelector("h1");
    const name = nameElement?.textContent?.trim() || "there";

    const titleElement =
      document.querySelector('[data-anonymize="title"]') ||
      document.querySelector(".artdeco-entity-lockup__subtitle") ||
      document.querySelector(".pv-top-card--list-bullet li");
    const title = titleElement?.textContent?.trim() || "professional";

    const companyElement =
      document.querySelector('[data-anonymize="company-name"]') ||
      document.querySelector(".artdeco-entity-lockup__caption a") ||
      document.querySelector(".pv-top-card--experience-list-single-position");
    const company_name = companyElement?.textContent?.trim() || "your company";

    const companyLink = document.querySelector(
      'a[href*="/sales/company/"], a[href*="/company/"]'
    ) as HTMLAnchorElement | null;
    let company_linkedin_url = "";
    if (companyLink) {
      const href = companyLink.getAttribute("href") || "";
      company_linkedin_url = href.startsWith("http")
        ? href.split("?")[0]
        : `https://www.linkedin.com${href.split("?")[0]}`;
    }

    return {
      name,
      title,
      company_name,
      company_linkedin_url,
    };
  } catch (error) {
    console.error("Papooga: Error extracting profile data:", error);
    return null;
  }
}

function createPasteButton(textarea: HTMLTextAreaElement): HTMLElement {
  const button = document.createElement("button");
  button.className = PASTE_BTN_CLASS;
  button.textContent = "Paste Papooga Note";
  button.type = "button";

  button.addEventListener("click", (e) => {
    e.preventDefault();
    e.stopPropagation();

    const profileData = extractCurrentProfileData();
    if (!profileData) {
      alert("Could not extract profile data. Please try again.");
      return;
    }

    const note = generateConnectionNote(profileData);

    // Fill the textarea
    textarea.value = note;

    // Trigger input event so LinkedIn registers the change
    textarea.dispatchEvent(new Event("input", { bubbles: true }));
    textarea.dispatchEvent(new Event("change", { bubbles: true }));

    // Focus the textarea
    textarea.focus();

    // Visual feedback
    button.textContent = "Note pasted!";
    button.classList.add("papooga-paste-note-btn-success");
    setTimeout(() => {
      button.textContent = "Paste Papooga Note";
      button.classList.remove("papooga-paste-note-btn-success");
    }, 2000);
  });

  return button;
}

function checkForConnectionModal() {
  // Look for the "Add a note" modal/textarea
  // Sales Navigator uses different selectors than regular LinkedIn
  const textareas = document.querySelectorAll(
    'textarea[name="message"], textarea.connect-button-send-invite__custom-message, textarea[id*="connect"], textarea.artdeco-text-input'
  );

  textareas.forEach((textarea) => {
    const parent = textarea.parentElement;
    if (!parent) return;

    // Check if we already added a button
    if (parent.querySelector(`.${PASTE_BTN_CLASS}`)) return;

    // Add our paste button
    const button = createPasteButton(textarea as HTMLTextAreaElement);
    parent.insertBefore(button, textarea);
  });
}

export function initConnectionModal() {
  // Check immediately
  checkForConnectionModal();

  // Watch for modal appearing
  const observer = new MutationObserver((mutations) => {
    const hasNewNodes = mutations.some(
      (m) => m.addedNodes.length > 0
    );
    if (hasNewNodes) {
      // Small delay to let the modal render
      setTimeout(checkForConnectionModal, 100);
    }
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true,
  });
}
