-- Add Apollo enrichment fields to people table
ALTER TABLE people ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS email_status TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS headline TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS seniority TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS twitter_url TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS github_url TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS facebook_url TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS departments TEXT[];
ALTER TABLE people ADD COLUMN IF NOT EXISTS apollo_id TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS apollo_enriched_at TIMESTAMPTZ;
